version: 0.2

env:
  variables:
      env: "production"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - npm install
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - npm run build
#   post_build:
    # commands:
    #   - mkdir build
    #   - mkdir build/dist
    #   - cp index.html build/index.html
    #   - mv dist/* build/dist
artifacts:
  files:
    - index.html
    - dist
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - pathsversion: 0.2  env: 